const eventTagsLib = [
  { tagId: 1, eventId: 1 },
  { tagId: 1, eventId: 2 },
  { tagId: 1, eventId: 3 },
  { tagId: 2, eventId: 1 },
  { tagId: 2, eventId: 2 },
  { tagId: 2, eventId: 4 },
  { tagId: 2, eventId: 5 },
  { tagId: 3, eventId: 6 },
  { tagId: 3, eventId: 7 },
  { tagId: 3, eventId: 1 },
  { tagId: 3, eventId: 2 },
  { tagId: 4, eventId: 4 },
  { tagId: 4, eventId: 8 },
  { tagId: 4, eventId: 7 },
  { tagId: 4, eventId: 9 },
  { tagId: 5, eventId: 10 },
  { tagId: 5, eventId: 11 },
  { tagId: 5, eventId: 1 },
  { tagId: 6, eventId: 3 },
  { tagId: 6, eventId: 6 },
  { tagId: 6, eventId: 8 },
  { tagId: 6, eventId: 11 },
  { tagId: 6, eventId: 4 },
];

export default eventTagsLib;
