// populate with user events

const userEventsLib = [
  { userId: 1, eventId: 1 },
  { userId: 2, eventId: 1 },
  { userId: 3, eventId: 1 },
  { userId: 4, eventId: 1 },
  { userId: 10, eventId: 1 },
  { userId: 8, eventId: 1 },
  { userId: 1, eventId: 2 },
  { userId: 4, eventId: 2 },
  { userId: 10, eventId: 2 },
  { userId: 7, eventId: 2 },
  { userId: 5, eventId: 2 },
  { userId: 1, eventId: 3 },
  { userId: 10, eventId: 3 },
  { userId: 7, eventId: 3 },
  { userId: 4, eventId: 3 },
  { userId: 1, eventId: 4 },
  { userId: 6, eventId: 4 },
  { userId: 3, eventId: 4 },
  { userId: 1, eventId: 5 },
  { userId: 2, eventId: 6 },
  { userId: 4, eventId: 6 },
  { userId: 4, eventId: 7 },
  { userId: 1, eventId: 8 },
  { userId: 9, eventId: 8 },
  { userId: 8, eventId: 8 },
  { userId: 2, eventId: 8 },
  { userId: 4, eventId: 9 },
  { userId: 1, eventId: 9 },
  { userId: 2, eventId: 9 },
  { userId: 3, eventId: 9 },
  { userId: 5, eventId: 9 },
  { userId: 8, eventId: 9 },
  { userId: 3, eventId: 10 },
  { userId: 10, eventId: 10 },
  { userId: 5, eventId: 10 },
  { userId: 4, eventId: 11 },
  { userId: 2, eventId: 11 },
  { userId: 1, eventId: 11 },
];

export default userEventsLib;
